name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    name: Lint, Test, and Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Go fmt
        run: |
          go fmt ./...

      - name: Run Go vet
        run: |
          go vet ./...

      - name: Run unit tests
        run: |
          go test -v ./...

      - name: Build server
        run: |
          go build ./cmd/server

      - name: Build client
        run: |
          go build ./cmd/client
